vich_uploader:
    db_driver: orm

    metadata:
        type: annontations

    mappings:
       picture_profile:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            