index:
   path: /
   controller: App\Controller\MainController::index
auth:
    path: /api/login_check
    methods: ['POST']
# proteger route generative/.. pour l'acces user uniquement (personnes log)
# /profile uniquement pour les role user