index:
   path: /
   controller: App\Controller\MainController::index
api_login_check:
    path: /api/login_check
    methods: ['POST']
# api_refresh_token:
#     path: /api/refresh_token
#     controller: App\Controller\Api\api_TokenController::refreshToken
#     methods: ['POST']

# proteger route generative/.. pour l'acces user uniquement (personnes log)
# /profile uniquement pour les role user